### ISSUE TITLE
Dispatcher won't start

### ISSUE THREAD

**Issue by letmejustfixthatohitsbroken** [mikrosimage/OpenRenderManagement#29]
Hello,

I hope this project is still managed since it sounds really nice. How ever, I tried to get the Dispatcher running all day.

Some infos:
- Freshly installed Fedora 22 Server, a few more packages are required
```console
yum -y gcc mysql-devel git
```
- Followed the instruction, some of those seem to be a bit out of date
Changed this
```console
cp -R ~/OpenRenderManagement/Puli/src/octopus/ /opt/puli/
cp -R ~/OpenRenderManagement/Puli/scripts/ /opt/puli/
cp -R ~/OpenRenderManagement/Puli/etc/puli /opt/puli/conf/
```
to
```console
cp -R ~/OpenRenderManagement/src/octopus/ /opt/puli/
cp -R ~/OpenRenderManagement/scripts/ /opt/puli/
cp -R ~/OpenRenderManagement/etc/puli /opt/puli/conf/
```

Next, the dispatcher has moved I suppose, so I used 
```console
 python /opt/puli/octopus/dispatcherd.py --debug --console
```

The result I always get is:

```console
Traceback (most recent call last):
  File "/opt/puli/octopus/dispatcherd.py", line 33, in <module>
    from octopus.dispatcher.webservice.webservicedispatcher import WebServiceDispatcher
  File "/opt/puli/octopus/dispatcher/webservice/__init__.py", line 51, in <module>
    from .webservicedispatcher import WebServiceDispatcher as WebService
  File "/opt/puli/octopus/dispatcher/webservice/webservicedispatcher.py", line 22, in <module>
    from octopus.dispatcher.webservice import commands, rendernodes, graphs, nodes,\
  File "/opt/puli/octopus/dispatcher/webservice/rendernodes.py", line 21, in <module>
    from puliclient.model.renderNode import RenderNode as RenderNodeModel
ImportError: No module named puliclient.model.renderNode
```

Any ideas?

Here the config file

```python
#!/usr/bin/python
# -*- coding: utf8 -*-

"""
Module holding core value for the dispatcher process.
These values might be overriden by user arguments and should not be reloaded.
Value which could be reloaded during execution (using "reconfig" webservice)
should be defined in "settings.py".
"""
__author__ = "Arnaud Chassagne"
__copyright__ = "Copyright 2010, Mikros Image"


import os

def getLocalAddress():
    import socket
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(('0.0.0.0', 56))
        return s.getsockname()[0]
    except:
        return "127.0.0.1"


def loadSettingsFile(filename):
    g = {}
    l = {}
    execfile(filename, g, l)
    settings = ((name, value) for name, value in l.items() if name.isupper() and name in globals())
    globals().update(settings)


## SETTINGS ###########################################################

VERSION = os.environ.get("REZ_PULI_VERSION", '-')

DEBUG = False

PORT = 8004
ADDRESS = getLocalAddress()
RUN_AS = None


#
# LOG AND CONF FOLDERS
#
LOGDIR = "/opt/puli/logs"
CONFDIR = "/opt/puli/conf"

#
# COMMAND LAUNCHED DURING SHUTDOWN TO RESTART SERVER
#
RESTART_COMMAND = "sudo systemctl restart puliserver.service"

#
# SERVICE CONTROL PID FILE
#
PIDFILE = "/var/run/puli/dispatcher.pid"
#
# PERSISTENCE MECANISM
#
#POOLS_BACKEND_TYPE = "db"
POOLS_BACKEND_TYPE = "file"
#POOLS_BACKEND_TYPE = "ws"

FILE_BACKEND_RN_PATH = os.path.join(CONFDIR, "workers.lst")
FILE_BACKEND_LICENCES_PATH = os.path.join(CONFDIR, "licences.lst")
FILE_BACKEND_POOL_PATH = os.path.join(CONFDIR, "pools")
WS_BACKEND_URL = ""
WS_BACKEND_PORT = 11800

DB_ENABLE = True
DB_CLEAN_DATA = True

DB_URL = "mysql://puliuser:renderit@127.0.0.1/pulidb"
STAT_DB_URL = "__STAT_DB_URL_PLACEHOLDER__"
```

**Comment by teskenazi** [comment]
Hello,

Thanks for using this project!

Regarding your issue, it seems that the $PYTHONPATH is not correctly resolved by python. Did you export it as it is stated in this documentation https://github.com/mikrosimage/OpenRenderManagement#installation ?
